# Used when building external pull requests
# We don't want to publish build artifacts or expose our other caches to possibly untrusted code
# Reference https://github.com/CaffeineMC/sodium/blob/dc7dc4c634316ac8b510d2dc8290079ebc462778/.github/workflows/build-pull-request.yml
name: build-pull-request

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Pakku
        run: curl -L -o pakku.jar https://github.com/juraj-hrivnak/Pakku/releases/download/v1.3.2/pakku.jar

      - name: Export modpack
        run: java -jar pakku.jar export


      - name: Upload Curseforge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wxrldssoptimisations-cf-artifacts-pr
          path: build/curseforge/*.zip

      - name: Upload Modrinth Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wxrldssoptimisations-mr-artifacts-pr
          path: build/modrinth/*.mrpack
